# Generated by Django 5.0.1 on 2024-01-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_create',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='blog_create',
            name='body',
        ),
        migrations.AddField(
            model_name='blog_create',
            name='course',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog_create',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
