# Generated by Django 5.0.1 on 2024-01-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_title_blog_create_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_create',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='blog_create',
            name='surname',
            field=models.CharField(max_length=15),
        ),
    ]
