# Generated by Django 5.0.1 on 2024-01-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_blog_create_name_alter_blog_create_surname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_create',
            new_name='BlogM',
        ),
    ]
